version: '3.8'

services:
  # Servicio de Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - hospital-network

  # Servicio de Backend (ajusta según tu configuración real)
  backend:
    image: backend-image:latest  # Reemplaza con tu imagen de backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=hospital
    depends_on:
      - database
      - mqtt-broker
    networks:
      - hospital-network

  # Base de datos (PostgreSQL)
  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hospital
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hospital-network

  # Broker MQTT (HiveMQ)
  mqtt-broker:
    image: hivemq/hivemq-ce:latest
    ports:
      - "1883:1883"  # Puerto MQTT
      - "8083:8083"  # Puerto WebSockets
    volumes:
      - mqtt-data:/opt/hivemq/data
    networks:
      - hospital-network

networks:
  hospital-network:
    driver: bridge

volumes:
  postgres-data:
  mqtt-data: